server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;
  error_page 404 /404.html;

  location = /tapoo {
    return 301 /tapoo/;
  }

  location ^~ /tapoo/ {
    rewrite ^/tapoo/(.*)$ /$1 break;
    try_files $uri $uri.html $uri/ =404;
  }

  location ~* \.html$ {
    add_header Cache-Control "no-store";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri.html $uri/ =404;
  }
}
